## AdaBoosting and Gradient Boosting Model 
### Import necessary libraries 

In [54]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pickle
import functions as fn
from sklearn.model_selection import train_test_split, cross_val_score, KFold
from sklearn.preprocessing import OneHotEncoder
# Boosting library
from sklearn.model_selection import cross_val_score, KFold
from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix, classification_report

### Run data_prep.ipynb and open pickle X_train, X_test, y_train, y_test. 

In [55]:
% run ./data_prep.ipynb

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11914 entries, 0 to 11913
Data columns (total 16 columns):
Make                 11914 non-null object
Model                11914 non-null object
Year                 11914 non-null int64
Engine Fuel Type     11911 non-null object
Engine HP            11845 non-null float64
Engine Cylinders     11884 non-null float64
Transmission Type    11914 non-null object
Driven_Wheels        11914 non-null object
Number of Doors      11908 non-null float64
Market Category      8172 non-null object
Vehicle Size         11914 non-null object
Vehicle Style        11914 non-null object
highway MPG          11914 non-null int64
city mpg             11914 non-null int64
Popularity           11914 non-null int64
MSRP                 11914 non-null int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.5+ MB


./data_prep.ipynb:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  {
./data_prep.ipynb:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  {
/anaconda3/envs/learn-env/lib/python3.7/site-packages/pandas/core/indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s


<class 'pandas.core.frame.DataFrame'>
Int64Index: 7856 entries, 0 to 11912
Data columns (total 16 columns):
Make                 7856 non-null object
Model                7856 non-null object
Year                 7856 non-null int64
Engine Fuel Type     7856 non-null object
Engine HP            7856 non-null float64
Engine Cylinders     7856 non-null float64
Transmission Type    7856 non-null object
Driven_Wheels        7856 non-null object
Number of Doors      7856 non-null float64
Market Category      6219 non-null object
Vehicle Size         7856 non-null object
Vehicle Style        7856 non-null object
highway MPG          7856 non-null int64
city mpg             7856 non-null int64
Popularity           7856 non-null int64
MSRP                 7856 non-null int64
dtypes: float64(3), int64(5), object(8)
memory usage: 1.0+ MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 6219 entries, 0 to 11912
Data columns (total 16 columns):
Make                 6219 non-null object
Model     

./data_prep.ipynb:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  {
./data_prep.ipynb:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  {
/anaconda3/envs/learn-env/lib/python3.7/site-packages/pandas/core/frame.py:3697: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


<class 'pandas.core.frame.DataFrame'>
Int64Index: 5966 entries, 0 to 11912
Data columns (total 15 columns):
Make                 5966 non-null object
Model                5966 non-null object
Year                 5966 non-null int64
Engine Fuel Type     5966 non-null object
Engine HP            5966 non-null float64
Engine Cylinders     5966 non-null float64
Transmission Type    5966 non-null object
Driven_Wheels        5966 non-null object
Market Category      5966 non-null object
Vehicle Size         5966 non-null object
Vehicle Style        5966 non-null object
highway MPG          5966 non-null int64
city mpg             5966 non-null int64
Popularity           5966 non-null int64
MSRP                 5966 non-null int64
dtypes: float64(2), int64(5), object(8)
memory usage: 745.8+ KB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 5966 entries, 0 to 11912
Data columns (total 23 columns):
Year                 5966 non-null int64
Engine Fuel Type     5966 non-null object
Engine HP 

In [56]:
with open('X_train.pickle', 'rb') as f:
    X_train = pickle.load(f)
    
with open('X_test.pickle', 'rb') as f:
    X_test = pickle.load(f)
    
with open('y_train.pickle', 'rb') as f:
    y_train = pickle.load(f)
    
with open('y_test.pickle', 'rb') as f:
    y_test = pickle.load(f)

In [57]:
# Drop feature Popularity because feature is not clear how the popularity is measure.
del X_train['Popularity']
del X_test['Popularity']


In [58]:
# Assign classifiers
adaboost_clf = AdaBoostClassifier()
gbt_clf = GradientBoostingClassifier()

In [59]:
# Train each of the classifieres using training data
adaboost_clf.fit(X_train, y_train)
gbt_clf.fit(X_train, y_train)

GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=3,
                           max_features=None, max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=1, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=100,
                           n_iter_no_change=None, presort='auto',
                           random_state=None, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False)

In [60]:
# Create predictions using each model to calculate the training and testing accuracy for each.
adaboost_train_preds = adaboost_clf.predict(X_train)
adaboost_test_preds = adaboost_clf.predict(X_test)
gbt_clf_train_preds = gbt_clf.predict(X_train)
gbt_clf_test_preds = gbt_clf.predict(X_test)

### Calculate the training and testing accuracy and f1-score for each model

In [61]:
print("Training Metrics:")
print("Accuracy:", accuracy_score(y_train, adaboost_train_preds))
print("Accuracy:", accuracy_score(y_train, gbt_clf_train_preds))

print("Test Metrics:")
print("F1-Score", f1_score(y_test, adaboost_test_preds, average='micro'))
print("F1-Score", f1_score(y_test, gbt_clf_test_preds, average='micro'))

Training Metrics:
Accuracy: 0.5165400089405454
Accuracy: 0.9696021457308895
Test Metrics:
F1-Score 0.514745308310992
F1-Score 0.9323056300268097


### Create a confusion matrix and classification report for adaboost & Gradient Boosting

In [62]:
# Create a confusion matrix and classification report for adaboost 
adaboost_confusion_matrix = confusion_matrix(y_test, adaboost_test_preds)
print("Confusion Matrix:")
print(adaboost_confusion_matrix)

adaboost_classification_report = classification_report(y_test, adaboost_test_preds)
print("\n")
print(adaboost_classification_report)

Confusion Matrix:
[[192  37   0  47  37   4   0]
 [  2  15   0  12   0   8   0]
 [  2   0   0   0  62   0   0]
 [ 59  37   0 263 101   0   0]
 [ 11   6   0 183 278   0   0]
 [  3  19   0   0  22  20   0]
 [  0   4   0  63   5   0   0]]


              precision    recall  f1-score   support

           0       0.71      0.61      0.66       317
           1       0.13      0.41      0.19        37
           2       0.00      0.00      0.00        64
           3       0.46      0.57      0.51       460
           4       0.55      0.58      0.57       478
           5       0.62      0.31      0.42        64
           6       0.00      0.00      0.00        72

    accuracy                           0.51      1492
   macro avg       0.35      0.35      0.33      1492
weighted avg       0.50      0.51      0.50      1492



/anaconda3/envs/learn-env/lib/python3.7/site-packages/sklearn/metrics/classification.py:1437: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [63]:
# Create a confusion matrix and classification report for gbt 
gbt_confusion_matrix = confusion_matrix(y_test, gbt_clf_test_preds)
print("Confusion Matrix:")
print(gbt_confusion_matrix)

gbt_classification_report = classification_report(y_test, gbt_clf_test_preds)
print("\n")
print(gbt_classification_report)

Confusion Matrix:
[[301   0   0  14   2   0   0]
 [  2  35   0   0   0   0   0]
 [  0   0  61   3   0   0   0]
 [  7   0   1 434  18   0   0]
 [ 11   0   1  21 443   0   2]
 [  0   2   0   0   0  62   0]
 [  0   0   0   8   9   0  55]]


              precision    recall  f1-score   support

           0       0.94      0.95      0.94       317
           1       0.95      0.95      0.95        37
           2       0.97      0.95      0.96        64
           3       0.90      0.94      0.92       460
           4       0.94      0.93      0.93       478
           5       1.00      0.97      0.98        64
           6       0.96      0.76      0.85        72

    accuracy                           0.93      1492
   macro avg       0.95      0.92      0.93      1492
weighted avg       0.93      0.93      0.93      1492



### Use fn to call out adaboost and gbt functions to calculate cross validation score for both train and test data. Compute the mean cross validation score for each model. Also cv set to cv=10. 

In [64]:
fn.adaboost(X_train, X_test, y_train, y_test)

Mean Adaboost Cross-Val Score (k=10):
train: 0.5134388437043073, test: 0.4820237628874297


In [65]:
fn.gbt(X_train, X_test, y_train, y_test)`

SyntaxError: invalid syntax (<ipython-input-65-8a5f3555a78e>, line 1)